version: "3"
services:
  api:
    build: api
    ports:
      - "3000:3000"
    environment:
      - BASE_URL=${BASE_URL}
    depends_on:
      - db

  db:
    build: db
    ports:
      - "6379:6379"
    volumes:
      - .data:/data/